# SPDX-License-Identifier: Apache-2.0

releases:
  # Another microservice
  - name: admin-service
    namespace: processor
    # When using OCI, the full URI must be specified in the chart field.
    chart: oci://docker.io/tazamaorg/admin-service-helm
    version: 0.1.0
    installed: {{ if hasKey .Values "installAdminService" }}{{ .Values.installAdminService | default true }}{{ else }}true{{ end }}
    labels:
      tier: core
      env: dev
    values:
      - ../values/admin-service.yaml