apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tazama-workload.fullname" . }}
  labels:
    {{- include "tazama-workload.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
