# SPDX-License-Identifier: Apache-2.0
fullnameOverride: tazama-postgres-init
credentialsSecretName: tazama-credentials
postgres:
  username: postgres
  password: unused
  replicationPassword: unused
valkey:
  password: ""
keycloak:
  adminUser: admin
  adminPassword: password
  clientSecret: auth-lib-client-test-secret
auth:
  publicKey: ""
  privateKey: ""
createPullSecret: false
pullSecretName: frmpullsecret
dockerServer: https://index.docker.io/v1/
dockerUsername: ""
dockerPassword: ""
dockerEmail: ""
