# SPDX-License-Identifier: Apache-2.0

installBatchPPA: true

replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: tazamaorg/batch-ppa
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "4.0.0"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  - name: frmpullsecret
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations:
  prometheus.io/scrape: "false"
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  hosts:
    - host: batch-ppa.approval.test.lf
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: batch-ppa-tls
      hosts:
        - batch-ppa.approval.test.lf

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

env:
  NPM_CONFIG_LOGLEVEL: "warn"
  mode: "http"
  upstream_url: "http://0.0.0.0:3000"
  exec_timeout: "10s"
  write_timeout: "15s"
  read_timeout: "15s"
  prefix_logs: "false"
  FUNCTION_NAME: "batch-ppa"
  NODE_ENV: "production"
  MAX_CPU: "1"
  TMS_ENDPOINT: ""
  QUOTING: "true"
  PORT: "4100"
  AUTHENTICATED: "false"
  CERT_PATH_PUBLIC: ""
  REDIS_DATABASE: "0"
  REDIS_AUTH: ""
  REDIS_SERVERS: '[{"host":"valkey.processor.svc.cluster.local", "port":6379}]'
  REDIS_IS_CLUSTER: "true"
  DISTRIBUTED_CACHETTL: "300"
  DISTRIBUTED_CACHE_ENABLED: "true"
  PSEUDONYMS_DATABASE: "pseudonyms"
  PSEUDONYMS_DATABASE_URL: "tcp://0.0.0.0:8529"
  PSEUDONYMS_DATABASE_USER: "root"
  PSEUDONYMS_DATABASE_PASSWORD: ""
  PSEUDONYMS_DATABASE_CERT_PATH: ""
  TRANSACTION_HISTORY_DATABASE: "transactionHistory"
  TRANSACTION_HISTORY_DATABASE_URL: "tcp://0.0.0.0:8529"
  TRANSACTION_HISTORY_DATABASE_USER: "root"
  TRANSACTION_HISTORY_DATABASE_PASSWORD: ""
  TRANSACTION_HISTORY_DATABASE_CERT_PATH: ""
  APM_ACTIVE: "false"
  APM_SERVICE_NAME: "batch-ppa"
  APM_URL: "http://apm:8200"
  APM_SECRET_TOKEN: ""
  LOGSTASH_HOST: "logstashhost"
  LOGSTASH_PORT: "8080"